from pathlib import Path
p=Path(__file__).resolve().parent/'policies';p.mkdir(exist_ok=True)
policies=[
('Information Security','SEC-001','Restricted documents require authenticated authorization and role verification for every retrieval. Public material may be shared externally after content review. Internal documents are only for staff. Every access to a restricted document must be auditable. Never place document text into an AI prompt until the requester passes document-level access checks.','Security','Quarterly'),
('Data Retention','GOV-002','Incident records are retained for 36 months following closure. Financial transaction evidence is retained for seven years. Requests for deletion must be evaluated against applicable legal holds and recordkeeping duties. Synthetic test records may be discarded when a test concludes.','Legal','Annual'),
('Supplier Onboarding','PRC-003','Procurement validates supplier identity, tax details, beneficial ownership disclosures, and bank-account changes through a separate verification channel. High-risk suppliers require Security and Legal review before purchase orders are approved.','Procurement','Annual'),
('Incident Escalation','OPS-004','Critical incidents are escalated immediately to the on-call incident commander and Security if data access may be involved. High priority incidents require a same-day owner and written action plan. The post-incident review records timeline, customer impact, and corrective actions.','Operations','Semiannual'),
('Employee Joiner-Mover-Leaver','HR-005','People Operations initiates onboarding. Managers request minimum necessary access. Security reviews privileged accounts. On termination, access is revoked in accordance with the offboarding checklist and any preserved evidence obligations.','People Operations','Quarterly'),
('Payment Reconciliation','FIN-006','Finance reconciles payment processor settlement files with invoice, ledger, and bank records. Variances are tracked under case identifiers and assigned to an independent reviewer. Adjustments require documented approval.','Finance','Monthly'),
('Customer Escalation','CS-007','Customer Success logs a case reference, severity, impact, owner, and promised update time. Critical-impact cases trigger joint coordination with Engineering and Operations. Personal data must not be included in non-restricted case summaries.','Customer Success','Quarterly'),
('Change Management','ENG-008','Production changes require a ticket, peer review, verification steps, rollback instructions, and deployment owner. Emergency changes receive retrospective review by the following business day.','Engineering','Quarterly'),
('Access Reviews','SEC-009','Resource owners review assigned access quarterly. Privileged and service-account access is reviewed separately. Exceptions are time bounded, documented, and approved by a designated control owner.','Security','Quarterly'),
('Invoice Approval','FIN-010','Invoices must match a valid purchase order and receiving evidence when applicable. The requestor and payment approver must be separate people for controlled purchases. Any exception requires a recorded reason.','Finance','Quarterly'),
('Warehouse Inventory','OPS-011','Warehouse teams perform cycle counts based on item criticality. Discrepancies must cite warehouse, item, count date, and adjustment authorization. Inventory records are reconciled before month close.','Operations','Monthly'),
('Project Reporting','PM-012','Project status reports document milestone, risks, budget category, accountable owner, and next checkpoint. Critical risks are not marked closed without evidence that the mitigation was verified.','Engineering','Monthly'),
('Analytics Definitions','ANA-013','Net sales equals gross sales minus discounts in the fictional financial dataset. Profit equals sales minus cost of goods sold where that accounting definition applies. Percent-of-total results use the same filters in numerator and denominator.','Analytics','Quarterly'),
('AI Assistant Retrieval','AI-014','The assistant retrieves permitted document excerpts and cites their document identifiers. Numeric facts in the finance database must come from authorized SQL reporting tools, not from free-form document snippets. When source content is missing, the assistant explains that it cannot verify the requested answer.','Analytics','Quarterly'),
('RAG Data Quality','AI-015','Retrieval evaluation reports recall at k, citation precision, refusal accuracy, p50/p95 latency, and ingest throughput. A million synthetic records measures throughput and filtering performance but does not prove real-world semantic relevance without a curated evaluation set.','Analytics','Monthly'),
('Confidentiality Labels','GOV-016','The three demonstration labels are public, internal, and restricted. Classification follows sensitivity, not the document type alone. Production authorization requires the user identity and entitlements from the backend; a user-supplied access-level flag is not trusted.','Legal','Quarterly'),
('Audit Evidence Handling','AUD-017','Each evidence item includes a stable document ID, collection time, control reference, reviewer, and retention assignment. Audit documents are immutable after sign-off; amendments create a superseding revision with a linked explanation.','Legal','Annual'),
('Business Continuity','OPS-018','Critical services maintain restoration objectives, backups, alternate contacts, and periodic recovery exercises. After an outage, owners capture detection, mitigation, and recovery timestamps and record lessons learned.','Operations','Annual'),
('Model Evaluation','AI-019','A retrieval benchmark has a fixed query set with known relevant document identifiers. Report recall at five and ten, latency distribution, unauthorized-document leakage, and answer attribution separately. Re-running the same queries after re-indexing enables comparison.','Analytics','Monthly'),
('Embedding Pipeline','AI-020','Documents are cleaned, segmented, embedded, and indexed in small batches. Keep source IDs and access controls on every chunk. Upsert by stable document and chunk identifier, and re-embed only when the source or model version changes.','Engineering','Quarterly'),
('Marketing Claims','MKT-021','Public performance claims must be traceable to an approved source and review date. Estimates and synthetic examples must be labeled clearly. Sales may not present synthetic record counts as actual customer outcomes.','Sales','Annual'),
('Financial Close','FIN-022','Finance finalizes accruals, reconciliations, and variance explanations before close approval. Post-close corrections are documented with period reference, reviewer, and supporting evidence.','Finance','Monthly'),
('Customer Data Minimization','SEC-023','Support cases include only fields necessary for investigation. Production personal data is not permitted in development fixtures. Logs and embeddings must honor deletion workflows and retention policies.','Security','Quarterly'),
('Release Readiness','ENG-024','The release checklist requires passing unit tests, authorization checks, rollback readiness, database migration review, and an owner for incident response. Failed security checks block the release.','Engineering','Monthly'),
]
for title,code,body,owner,cycle in policies:
    text=f'''# {title}\n\n**Company:** COMPANY (fictional test enterprise)  \n**Document ID:** POLICY-{code}  \n**Owner:** {owner}  \n**Review cycle:** {cycle}  \n**Classification:** Internal (synthetic; safe test fixture)  \n**Version:** 1.0  \n\n## Purpose\nThis policy is a fictional benchmark reference for testing retrieval, citation and access handling in Bundle Data Assistant. It is not an approved policy for a real organization.\n\n## Requirements\n{body}\n\n## Evidence expectations\nFor every use of this policy, show the policy ID as the source and do not invent approvals, dates, or exceptions. Apply the access label and verify any operational assertions using the appropriate system of record.\n'''
    (p/f'{code.lower()}_{title.lower().replace(" ","_")}.md').write_text(text,encoding='utf8')
print(f'Wrote {len(policies)} policy markdown documents')
